package utils;

import android.graphics.Color;

/**
 * Class for retrieving Colors used in the StoryTeller color palette
 *
 * Color Palette generated by Coolors at:
 * http://coolors.co/app/071013-75abbc-1295f9-a2aebb-dfe0e2
 */

public class ColorPalette {

    /**
     * @return Color.argb(255, 18, 149, 249)
     */
    public static int getBlue(){

        return Color.argb(255, 18, 149, 249);

    }

    /**
     * @return Color.argb(255, 7, 16, 19)
     */
    public static int getBlack(){

        return Color.argb(255, 7, 16, 19);

    }

    /**
     * @return Color.argb(255, 117, 171, 188)
     */
    public static int getGreen(){

        return Color.argb(255, 117, 171, 188);

    }

    /**
     * @return Color.argb(255, 162, 174, 187)
     */
    public static int getGrey(){

        return Color.argb(255, 162, 174, 187);

    }

    /**
     * @return Color.argb(255, 223, 224, 226)
     */
    public static int getWhite(){

        return Color.argb(255, 223, 224, 226);

    }


}
